name: Deploy Site

on:
  workflow_run:
    workflows: ['Release']
    branches: [main]
    types: 
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Website
        working-directory: ${{ inputs.directory }}
        run: yarn --frozen-lockfile
      
      - name: Build website
        working-directory: ${{ inputs.directory }}
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
